import type { AIProviderConfig } from "@/types/ai";
import { getProvider } from "./registry";
import { consoleLogger, type Logger } from "./logger";
import { LANGUAGE_POLISH_SYSTEM_PROMPT } from "./prompts";

/**
 * Final review pass over an assembled note: rewrites it for natural, correct,
 * human-sounding language, and smooths over any inconsistency introduced by
 * multi-part generation (different chunks can end up generated by different
 * fallback providers — see chunkedGeneration.ts). Tries enabled providers in
 * priority order, same as note generation itself. If every provider fails,
 * the original unpolished markdown is returned rather than losing the note.
 */
export async function polishNoteLanguage(
  markdown: string,
  configs: AIProviderConfig[],
  logger: Logger = consoleLogger,
): Promise<string> {
  const ordered = configs.filter((c) => c.enabled).sort((a, b) => a.priority - b.priority);

  if (ordered.length === 0) {
    logger.warn("no enabled AI provider to polish note language with — keeping note as generated");
    return markdown;
  }

  logger.info("reviewing note for natural, human-quality language…");

  for (const config of ordered) {
    const provider = getProvider(config.id);
    try {
      logger.info(`sending note to ${config.id} for language polish…`);
      const polished = await provider.complete(LANGUAGE_POLISH_SYSTEM_PROMPT, markdown, config);
      logger.info(`${config.id} polish completed (${polished.length} chars)`);
      return polished.trim();
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      logger.warn(`${config.id} polish failed, trying next: ${message}`);
    }
  }

  logger.warn("language polish failed on every provider — keeping the note as originally generated");
  return markdown;
}
